import type { Destination } from "@/lib/types";

// v1 seed content: 10 destinations (少而精, per Q10=A). Structure scales to 30+.
export const DESTINATIONS: Destination[] = [
  {
    id: "jp-countryside",
    country: { zh: "日本", en: "Japan" },
    city: { zh: "乡间田野", en: "Countryside" },
    lat: 36.2, lng: 138.2,
    climate: "temperate",
    terrain: ["photo", "rainproof"],
    season: ["summer", "autumn"],
    regionPref: ["asia"],
    rarity: "common",
    distanceTier: "near",
    blurb: { zh: "稻田与蝉鸣,慢悠悠的夏天。", en: "Rice fields and cicadas, a slow summer." },
    scenes: ["field", "roadside", "sunset"],
    souvenirPool: [
      { id: "jp-ticket", name: { zh: "一枚旧车票", en: "An old train ticket" } },
      { id: "jp-pebble", name: { zh: "一块普通石头", en: "An ordinary pebble" } },
      { id: "jp-teaspoon", name: { zh: "木制茶匙", en: "A wooden tea spoon" } },
      { id: "jp-cloth", name: { zh: "蓝染布片", en: "A scrap of indigo cloth" } },
    ],
    diaries: [
      { zh: "风把稻穗吹成了一片海。", en: "The wind turned the rice into a sea." },
      { zh: "在路边睡了一小会儿。", en: "Napped a little by the roadside." },
      { zh: "遇到一只也在赶路的猫。", en: "Met a cat also on its way somewhere." },
    ],
  },
  {
    id: "kyoto",
    country: { zh: "日本", en: "Japan" },
    city: { zh: "京都", en: "Kyoto" },
    lat: 35.01, lng: 135.77,
    climate: "temperate",
    terrain: ["photo", "rainproof"],
    season: ["autumn", "spring"],
    regionPref: ["asia"],
    rarity: "uncommon",
    distanceTier: "near",
    blurb: { zh: "红叶与石阶,古老的巷子。", en: "Maple leaves and stone steps, old lanes." },
    scenes: ["shrine", "alley", "rain"],
    souvenirPool: [
      { id: "ky-fox", name: { zh: "小狐狸挂件", en: "A little fox charm" } },
      { id: "ky-omamori", name: { zh: "一枚护身符", en: "A small omamori" } },
      { id: "ky-leaf", name: { zh: "一片红叶", en: "A single maple leaf" } },
      { id: "ky-bag", name: { zh: "红色布袋", en: "A red cloth pouch" } },
    ],
    diaries: [
      { zh: "在鸟居下躲了一场雨。", en: "Sheltered from rain beneath a torii." },
      { zh: "石板路被雨洗得发亮。", en: "The stone path shone, washed by rain." },
      { zh: "听见远处有木屐的声音。", en: "Heard wooden clogs somewhere far off." },
    ],
  },
  {
    id: "iceland",
    country: { zh: "冰岛", en: "Iceland" },
    city: { zh: "雷克雅未克", en: "Reykjavík" },
    lat: 64.15, lng: -21.94,
    climate: "cold",
    terrain: ["cold", "far"],
    season: ["winter", "autumn"],
    regionPref: ["nordic"],
    rarity: "rare",
    distanceTier: "rare",
    requiredTags: ["cold"],
    blurb: { zh: "极光与黑沙滩,风很大。", en: "Auroras and black sand, and lots of wind." },
    scenes: ["aurora", "coast", "snow"],
    souvenirPool: [
      { id: "is-stone", name: { zh: "一块火山石", en: "A piece of volcanic rock" } },
      { id: "is-wool", name: { zh: "一缕羊毛", en: "A tuft of wool" } },
      { id: "is-shell", name: { zh: "黑沙里的贝壳", en: "A shell from black sand" } },
      { id: "is-feather", name: { zh: "海鸟的羽毛", en: "A seabird feather" } },
    ],
    diaries: [
      { zh: "风把我的围巾吹成了一面旗子。", en: "The wind turned my scarf into a flag." },
      { zh: "天空绿了一整晚。", en: "The sky glowed green all night." },
      { zh: "找到一个很高的地方。", en: "Found a very high place." },
    ],
  },
  {
    id: "paris",
    country: { zh: "法国", en: "France" },
    city: { zh: "巴黎", en: "Paris" },
    lat: 48.86, lng: 2.35,
    climate: "temperate",
    terrain: ["photo"],
    season: ["spring", "autumn"],
    regionPref: ["europe"],
    rarity: "uncommon",
    distanceTier: "far",
    blurb: { zh: "河边的旧书摊与咖啡香。", en: "Riverside bookstalls and coffee." },
    scenes: ["river", "cafe", "roof"],
    souvenirPool: [
      { id: "pa-stamp", name: { zh: "一张旧邮票", en: "An old postage stamp" } },
      { id: "pa-page", name: { zh: "旧书的一页", en: "A page from an old book" } },
      { id: "pa-ribbon", name: { zh: "一段丝带", en: "A length of ribbon" } },
      { id: "pa-sugar", name: { zh: "方糖包装纸", en: "A sugar-cube wrapper" } },
    ],
    diaries: [
      { zh: "在河边看了很久的船。", en: "Watched the boats by the river for a while." },
      { zh: "面包的味道和家里不一样。", en: "The bread tasted different from home." },
      { zh: "被鸽子追着跑了一段。", en: "A pigeon chased me for a bit." },
    ],
  },
  {
    id: "swiss-valley",
    country: { zh: "瑞士", en: "Switzerland" },
    city: { zh: "山谷", en: "Alpine Valley" },
    lat: 46.6, lng: 8.0,
    climate: "cold",
    terrain: ["mountain", "cold"],
    season: ["summer", "winter"],
    regionPref: ["europe"],
    rarity: "uncommon",
    distanceTier: "far",
    requiredTags: ["mountain"],
    blurb: { zh: "牛铃与雪山,空气很甜。", en: "Cowbells and snowy peaks, sweet air." },
    scenes: ["meadow", "peak", "cabin"],
    souvenirPool: [
      { id: "sw-bell", name: { zh: "一枚小牛铃", en: "A tiny cowbell" } },
      { id: "sw-flower", name: { zh: "压干的野花", en: "A pressed wildflower" } },
      { id: "sw-cheese", name: { zh: "奶酪的蜡纸", en: "Waxed cheese paper" } },
      { id: "sw-rock", name: { zh: "山上的石子", en: "A stone from the mountain" } },
    ],
    diaries: [
      { zh: "爬到半山腰就躺下了。", en: "Lay down halfway up the mountain." },
      { zh: "牛铃响了一整个下午。", en: "Cowbells rang all afternoon." },
      { zh: "云比我走得还慢。", en: "The clouds moved slower than me." },
    ],
  },
  {
    id: "norway-fjord",
    country: { zh: "挪威", en: "Norway" },
    city: { zh: "峡湾", en: "Fjord" },
    lat: 61.0, lng: 7.0,
    climate: "cold",
    terrain: ["cold", "far", "mountain"],
    season: ["summer", "autumn"],
    regionPref: ["nordic"],
    rarity: "rare",
    distanceTier: "rare",
    requiredTags: ["cold"],
    blurb: { zh: "峭壁与深蓝的水。", en: "Cliffs and deep blue water." },
    scenes: ["fjord", "boat", "cliff"],
    souvenirPool: [
      { id: "no-driftwood", name: { zh: "一段浮木", en: "A piece of driftwood" } },
      { id: "no-scale", name: { zh: "一片鱼鳞", en: "A fish scale" } },
      { id: "no-moss", name: { zh: "一撮苔藓", en: "A pinch of moss" } },
    ],
    diaries: [
      { zh: "水面静得像镜子。", en: "The water was still as a mirror." },
      { zh: "坐船坐了很久很久。", en: "Rode the boat for a long, long time." },
      { zh: "回声在山谷里绕圈。", en: "Echoes circled the valley." },
    ],
  },
  {
    id: "chiang-mai",
    country: { zh: "泰国", en: "Thailand" },
    city: { zh: "清迈", en: "Chiang Mai" },
    lat: 18.79, lng: 98.98,
    climate: "warm",
    terrain: ["warm", "rainproof"],
    season: ["winter", "spring"],
    regionPref: ["asia"],
    rarity: "common",
    distanceTier: "near",
    blurb: { zh: "夜市与温热的雨。", en: "Night markets and warm rain." },
    scenes: ["market", "temple", "rain"],
    souvenirPool: [
      { id: "cm-umbrella", name: { zh: "迷你油纸伞", en: "A mini paper umbrella" } },
      { id: "cm-bead", name: { zh: "一颗木珠", en: "A wooden bead" } },
      { id: "cm-flower", name: { zh: "茉莉花环碎片", en: "A bit of jasmine garland" } },
      { id: "cm-coin", name: { zh: "一枚小铜币", en: "A little copper coin" } },
    ],
    diaries: [
      { zh: "吃了很多没见过的东西。", en: "Ate many things I'd never seen." },
      { zh: "雨下得温温的。", en: "The rain fell warm." },
      { zh: "灯笼把河水染成了橙色。", en: "Lanterns dyed the river orange." },
    ],
  },
  {
    id: "beijing-hutong",
    country: { zh: "中国", en: "China" },
    city: { zh: "北京胡同", en: "Beijing Hutong" },
    lat: 39.92, lng: 116.4,
    climate: "temperate",
    terrain: ["photo"],
    season: ["autumn", "spring"],
    regionPref: ["asia"],
    rarity: "common",
    distanceTier: "near",
    blurb: { zh: "灰墙、槐树与鸽哨。", en: "Grey walls, scholar trees, pigeon whistles." },
    scenes: ["alley", "courtyard", "sunset"],
    souvenirPool: [
      { id: "bj-whistle", name: { zh: "一只鸽哨", en: "A pigeon whistle" } },
      { id: "bj-brick", name: { zh: "一小块灰砖", en: "A small grey brick chip" } },
      { id: "bj-leaf", name: { zh: "一片槐树叶", en: "A scholar-tree leaf" } },
      { id: "bj-candy", name: { zh: "糖葫芦的竹签", en: "A candied-haw stick" } },
    ],
    diaries: [
      { zh: "鸽子从头顶掠过,带着哨声。", en: "Pigeons swept overhead, whistling." },
      { zh: "在槐树下坐了一会儿。", en: "Sat a while under a scholar tree." },
      { zh: "巷子深处有下棋的声音。", en: "Heard chess pieces deep in the lane." },
    ],
  },
  {
    id: "new-zealand",
    country: { zh: "新西兰", en: "New Zealand" },
    city: { zh: "牧场", en: "Highlands" },
    lat: -44.0, lng: 170.1,
    climate: "temperate",
    terrain: ["mountain", "photo", "far"],
    season: ["spring", "summer"],
    regionPref: ["oceania"],
    rarity: "uncommon",
    distanceTier: "far",
    blurb: { zh: "绿到发光的山与很多羊。", en: "Hills so green they glow, and many sheep." },
    scenes: ["meadow", "lake", "peak"],
    souvenirPool: [
      { id: "nz-wool", name: { zh: "一小团羊毛", en: "A small ball of wool" } },
      { id: "nz-fern", name: { zh: "一片银蕨", en: "A silver fern frond" } },
      { id: "nz-stone", name: { zh: "溪边的圆石", en: "A round creek stone" } },
    ],
    diaries: [
      { zh: "羊比人多得多。", en: "Far more sheep than people." },
      { zh: "湖面倒映着整座山。", en: "The lake mirrored the whole mountain." },
      { zh: "草地软得想打滚。", en: "The grass was soft enough to roll on." },
    ],
  },
  {
    id: "morocco",
    country: { zh: "摩洛哥", en: "Morocco" },
    city: { zh: "撒哈拉边缘", en: "Sahara Edge" },
    lat: 31.1, lng: -4.0,
    climate: "arid",
    terrain: ["arid", "warm", "far"],
    season: ["autumn", "spring"],
    regionPref: ["africa"],
    rarity: "rare",
    distanceTier: "rare",
    requiredTags: ["arid"],
    blurb: { zh: "红沙与漫天星光。", en: "Red sand and a sky full of stars." },
    scenes: ["dune", "market", "stars"],
    souvenirPool: [
      { id: "ma-sand", name: { zh: "一小瓶红沙", en: "A vial of red sand" } },
      { id: "ma-tile", name: { zh: "一片花砖", en: "A patterned tile chip" } },
      { id: "ma-thread", name: { zh: "一段染色线", en: "A dyed thread" } },
      { id: "ma-date", name: { zh: "一颗枣核", en: "A date pit" } },
    ],
    diaries: [
      { zh: "沙子在夜里变凉了。", en: "The sand turned cool at night." },
      { zh: "星星多得数不过来。", en: "More stars than I could count." },
      { zh: "骆驼看了我很久。", en: "A camel looked at me for a long time." },
    ],
  },
];

export const DESTINATION_MAP: Record<string, Destination> = Object.fromEntries(
  DESTINATIONS.map((d) => [d.id, d]),
);
